# This is a basic workflow that is manually triggered

name: Github Actions Chapter 4 - Develope a CI/CD workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

env: 
  APPLICATOIN_NAME: app2
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout new
      uses: actions/checkout@v2

    - name: Setup Java 9
      uses: actions/setup-java@2
      with:
        java-version: '9.0.4'
        java-package: 'jdk'
        architecture: x64

    - name: list project files and java version
      run: |
        ls -ltr
        java -version 

      
      
